# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d675473e6caa8c51eef121690e70adea3ef29464e04e015fdca868e4e8b40f056851796815caa18a76ba46373b8a03a137b4a1fd83ed6e7d5817c48a8fbe4ad7

test:
  secret_key_base: 0e2abb48b9941ebb8581cab38a2d421c162e631e04bdc873797a65f50c0871ff51d1837c98d25c8dc13e0c9bad643f521a766f1381c48001624e610e40a26852

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
